services:
  bot:
    image: ghcr.io/djnotes/madelineproto-container:main
    
    volumes:
      - ./bot.php:/app/app.php
      - ./session:/app/session
      - ./log:/app/log
    env_file:
     - ./bot.env
    
